### ISSUE TITLE
Very long "Name" entry breaks the form

### ISSUE THREAD

**Issue by CJBrew** [refinery/refinerycms-inquiries#132]
To reproduce: Enter a name longer than 255 characters

Error page:
ActiveRecord::StatementInvalid in Refinery::Inquiries::InquiriesController#create

PG::StringDataRightTruncation: ERROR:  value too long for type character varying(255)
: INSERT INTO "refinery_inquiries_inquiries" ("created_at", "email", "message", "name", "phone", "spam", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"

I think this should invalidate the form rather than throw an ActiveRecord exception. I can probably fix it to be so (but I'm no Rails expert).

**Comment by parndt** [comment]
Fixed by #134
