### ISSUE TITLE
Wrong name in the 'Confirmation' 'From' header

### ISSUE THREAD

**Issue by nulty** [refinery/refinerycms-inquiries#151]
When a user submits an inquiry and the confirmation email is sent, the header looks like this:

```
#{inquiry.name} [#{site_name}] <#{Refinery::Inquiries.from_name}@#{request.domain}>
```

This email is sent from the refinery site and shouldn't have the name of the person who made the inquiry in the FROM header.

Maybe there should be a setting for this name. "from_name" is already used for the address username. "from_address_name" might be more descriptive, and use the "from_human_name" for the first part .
```
#{Refinery::Inquiries.from_human_name} [#{site_name}] <#{Refinery::Inquiries.from_address_name}@#{request.domain}>
```

What do you think?

**Comment by fgro** [comment]
+1

**Comment by bricesanchez** [comment]
Could you provide us a Pull Request ?
