### ISSUE TITLE
Is it possible to implement multiple inquiry forms and or extend?

### ISSUE THREAD

**Issue by denisinla** [refinery/refinerycms-inquiries#152]
Currently the contact form works correctly, but I was wondering if theres a way to extend inquiries engine to have multiple forms.

**Comment by DriesS** [comment]
:+1:

**Comment by bricesanchez** [comment]
There is a form generator in Refinery : https://github.com/refinery/refinerycms/blob/master/core/lib/generators/refinery/form/USAGE

I could fix your problem.
