### ISSUE TITLE
All inquiries marked as spam

### ISSUE THREAD

**Issue by dgm** [refinery/refinerycms-inquiries#161]
No matter what I type into the default contact form, it flags as spam, and does not deliver a notification.

**Comment by simi** [comment]
Probably caused by https://github.com/resolve/filters_spam/blob/master/lib/filters_spam.rb#L21-L31. Can you provide example inquiry not passing that?

**Comment by dgm** [comment]
author : asd ddjjjdd
message :  Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.

**Comment by dgm** [comment]
remote: git@github.com:refinery/refinerycms-inquiries.git
  revision: 192b4a91f4a0a5c7a8b60431f757aa8cfa8230ed
  branch: master

  remote: https://github.com/refinery/refinerycms
  revision: 3e2002834f75a9215dbafc3ed324836b5390b399
  branch: master

**Comment by dgm** [comment]
It also logs:    spam score was -5

**Comment by dgm** [comment]
As I look look at that filters_spam gem ... it seems to me like it has very little positive rules... and a lot of arbitrary rules.   S=Could we have a way to make this spam filter optional?   or use akismet?

**Comment by simi** [comment]
You can stay notified by "spam" also via "
https://github.com/refinery/refinerycms-inquiries/blob/master/lib/generators/refinery/inquiries/templates/config/initializers/refinery/inquiries.rb.erb#L12"
configuration.

2015-05-26 1:39 GMT+02:00 dgm <notifications@github.com>:

**Comment by simi** [comment]
@dgm it should be easy to contribute config to disable default spam filter via config.

1. You'll need to add it [here](https://github.com/refinery/refinerycms-inquiries/blob/master/lib/refinery/inquiries/configuration.rb) (on by default).
2. Add it [here](https://github.com/refinery/refinerycms-inquiries/blob/master/lib/generators/refinery/inquiries/templates/config/initializers/refinery/inquiries.rb.erb)
3. Run [this block](https://github.com/refinery/refinerycms-inquiries/blob/master/app/models/refinery/inquiries/inquiry.rb#L8-L12) only when filter is on. You can access config attributes directly on `Refinery::Inquiries`.

Would you mind to contribute this?

**Comment by parndt** [comment]
@dgm any interest in this issue anymore?

**Comment by dgm** [comment]
IIRC, it should be done, I just haven't had time to look at it myself.

**Comment by parndt** [comment]
Yeah, I agree that it would be nice.

**Comment by parndt** [comment]
I had a few minutes so I implemented it in #162

**Comment by dgm** [comment]
:+1:  looks pretty straightforward!
