### ISSUE TITLE
Disabling spam results in an undefined method 'ham?'

### ISSUE THREAD

**Issue by map7** [refinery/refinerycms-inquiries#166]
I'm running refinerycms-inquiries (3.0.1) and when I disable the spam detection and try and send an email through the contact form I get the following error

```
NoMethodError in Refinery::Inquiries::InquiriesController#create
undefined method `ham?' for #<Refinery::Inquiries::Inquiry:0x007ff2940f6de0>
```

If I remark out the following if statement in inquiries_controller and try again it sends the email fine.
`          if @inquiry.ham? || Inquiries.send_notifications_for_inquiries_marked_as_spam
`

**Comment by bricesanchez** [comment]
See #167
