### ISSUE TITLE
An example of how to correctly use inquiries will be greate

### ISSUE THREAD

**Issue by thebravoman** [refinery/refinerycms-inquiries#170]
It is not clear from the readme file what exactly should be added to the views, what should be called and rendered. 

Found on the internet is the following fragment:
<div class='inquiries'>
                <%= render '/refinery/inquiries/inquiries/form', inquiry: @inquiry %>
              </div>

but a similar should also be added to readme to make it easier for people to directly use it.

**Comment by parndt** [comment]
Could you add to the readme please with advice that would have helped you?

**Comment by thebravoman** [comment]
I was not able to get the inquiry working for the time limit I have set to myself and I have postpone it for now. Because of this I do not fill confident to describe how others should use inquire. If I ever get back to it and manage to use it I will get back to this issue.

**Comment by bricesanchez** [comment]
@thebravoman Do you try to add the inquiry form on each pages ?
